export { default as Landing } from "./Landing";
export { default as SignIn } from "./SignIn";
export { default as UserType } from "./UserType";
export { default as SignUp } from "./SignUp";
export { default as Profile } from "./Profile";
export { default as Dashboard } from "./Dashboard";
export { default as Courses } from "./Courses";
export { default as InsDashboard } from "./InsDashboard";
export { default as InsProfile } from "./InsProfile";
